steps:
- id: 'Terraform init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform init \
       -backend-config="bucket=${PROJECT_ID}-terraform-state" \
       -backend-config="prefix=${REPO_NAME}"
  dir: /workspace/infra

- id: 'Terraform plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform plan
  dir: /workspace/infra
  env:
  - "TF_VAR_org_id=${_ORG_ID}"
  - "GOOGLE_PROJECT=${PROJECT_ID}"
  - "TF_VAR_inception_id=${_INCEPTION_ID}"

- id: 'Terraform apply'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     terraform apply -auto-approve
  dir: /workspace/infra
  env:
  - "TF_VAR_org_id=${_ORG_ID}"
  - "GOOGLE_PROJECT=${PROJECT_ID}"
  - "TF_VAR_inception_id=${_INCEPTION_ID}"

timeout: 1800s
